apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - api-deployment.yaml
  - script-deployment.yaml
  - prometheus-deployment.yaml
  - grafana-deployment.yaml

configMapGenerator:
  - name: prometheus-config
    files:
      - prometheus-config/prometheus.yml
  - name: grafana-datasource
    files:
      - grafana-config/datasources.yaml
  - name: grafana-dashboard-config
    files:
      - grafana-config/dashboards.yaml
  - name: grafana-dashboard-json
    files:
      - grafana-config/dashboard.json
