apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadtester
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadtester
  template:
    metadata:
      labels:
        app: loadtester
    spec:
      containers:
        - name: loadtester
          image: blutenherz/penguin-loadtester:v1
          env:
            - name: API_URL
              value: "http://api:8989/predict"
